#
# Copyright contributors to the Galasa project 
#
apiVersion: galasa.dev/v1alpha
kind: Release
metadata:
  name: galasa-release
release:
  version: 0.18.0
  
  
  
framework:
  bundles:
  - artifact: dev.galasa
    version: 0.17.0
    obr: true
    bom: true
    mvp: true
    javadoc: true
    
  - artifact: dev.galasa.framework
    version: 0.17.0
    obr: true
    bom: true
    mvp: true
    
  - artifact: galasa-boot
    version: 0.17.0
    mvp: true

    
  - artifact: dev.galasa.framework.docker.controller
    version: 0.16.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.k8s.controller
    version: 0.16.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.maven.repository
    version: 0.15.0
    obr: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.framework.maven.repository.spi
    version: 0.15.0
    obr: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.framework.resource.management
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.metrics
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.cps.etcd
    version: 0.17.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.ras.couchdb
    version: 0.17.0
    obr: true
    isolated: true
    
    
    
api:
  bundles:
  - artifact: dev.galasa.framework.api
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.api.authentication
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.api.bootstrap
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.api.cps
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.api.health
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.api.ras
    version: 0.17.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.api.runs
    version: 0.17.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.framework.api.testcatalog
    version: 0.16.0
    obr: true
    isolated: true

  - artifact: dev.galasa.framework.api.webui
    version: 0.17.0
    obr: true
    isolated: true
    
    
    
managers:
  bundles:

#
# Manager 
#  

  - artifact: dev.galasa.artifact.manager
    version: 0.16.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.artifact.manager.ivt
    version: 0.16.0
    obr: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.cicsts.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.cicsts.ceci.manager
    version: 0.15.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.cicsts.ceda.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.cicsts.ceda.manager.ivt
    version: 0.17.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.cicsts.cemt.manager
    version: 0.15.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.cicsts.cemt.manager.ivt
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.cicsts.resource.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.core.manager
    version: 0.15.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.core.manager.ivt
    version: 0.15.0
    obr: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.docker.manager
    version: 0.17.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.docker.manager.ivt
    version: 0.17.0
    obr: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.elasticlog.manager
    version: 0.15.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.elasticlog.manager.ivt
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.galasaecosystem.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true

  - artifact: dev.galasa.galasaecosystem.manager.ivt
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.http.manager
    version: 0.17.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.http.manager.ivt
    version: 0.15.0
    obr: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.ipnetwork.manager
    version: 0.17.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.java.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.java.ubuntu.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.java.windows.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.jmeter.manager
    version: 0.15.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.jmeter.manager.ivt
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.kubernetes.manager
    version: 0.17.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.kubernetes.manager.ivt
    version: 0.15.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.liberty.manager
    version: 0.15.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.linux.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.linux.manager.ivt
    version: 0.16.0
    obr: true
    isolated: true
    
  - artifact: dev.galasa.openstack.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.phoenix2.manager
    version: 0.15.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.selenium.manager
    version: 0.16.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.selenium.manager.ivt
    version: 0.16.0
    obr: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.textscan.manager
    version: 0.16.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.windows.manager
    version: 0.15.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.zosbatch.rseapi.manager
    version: 0.16.0
    obr: true
    bom: true
    mvp: true
    isolated: true
        
  - artifact: dev.galasa.zosbatch.zosmf.manager
    version: 0.16.0
    obr: true
    bom: true
    mvp: true
    isolated: true

  - artifact: dev.galasa.zosconsole.oeconsol.manager
    version: 0.15.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zosconsole.zosmf.manager
    version: 0.15.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zosfile.rseapi.manager
    version: 0.17.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zosfile.zosmf.manager
    version: 0.17.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zosliberty.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.zosliberty.angel.manager
    version: 0.17.0
    obr: true
    bom: true
    isolated: true
    
  - artifact: dev.galasa.zos.manager
    version: 0.17.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zos.manager.ivt
    version: 0.16.0
    obr: true
    mvp: true
    isolated: true
      
  - artifact: dev.galasa.zosprogram.manager 
    version: 0.15.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zosmf.manager
    version: 0.15.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zosrseapi.manager
    version: 0.16.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zostsocommand.ssh.manager
    version: 0.15.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zosunixcommand.ssh.manager
    version: 0.15.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zos3270.common
    version: 0.15.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zos3270.manager
    version: 0.16.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - artifact: dev.galasa.zos3270.manager.ivt
    version: 0.16.0
    obr: true
    mvp: true
    isolated: true
  
    
    
    
external:
  bundles:
  - group: com.google.code.gson
    artifact: gson
    version: 2.8.5
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - group: com.sun.activation
    artifact: jakarta.activation
    version: 2.0.0
    obr: true
    mvp: true
    isolated: true
    
  - group: com.sun.xml.bind
    artifact: jaxb-osgi
    version: 3.0.0
    obr: true
    
  - group: commons-codec
    artifact: commons-codec 
    version: 1.15
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - group: commons-collections
    artifact: commons-collections
    version: 3.2.2
    obr: true
    mvp: true
    isolated: true
    
  - group: commons-io
    artifact: commons-io
    version: 2.9.0
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - group: commons-lang
    artifact: commons-lang
    version: 2.6
    obr: true
    mvp: true
    isolated: true
    
  - group: commons-logging
    artifact: commons-logging
    version: 1.2
    obr: false
    bom: true
    mvp: true
    isolated: true
    
  - group: dev.galasa
    artifact: com.jcraft.jsch
    version: 0.1.55 
    obr: true
    mvp: true
    isolated: true
    
  - group: io.prometheus
    artifact: simpleclient
    version: 0.6.0
    obr: true
    mvp: true
    isolated: true
    
  - group: io.prometheus
    artifact: simpleclient_common
    version: 0.6.0
    obr: true
    isolated: true
    
  - group: io.prometheus
    artifact: simpleclient_httpserver
    version: 0.6.0
    obr: true
    isolated: true
    
  - group: io.prometheus
    artifact: simpleclient_hotspot
    version: 0.6.0
    obr: true
    isolated: true
    
  - group: jakarta.xml.bind
    artifact: jakarta.xml.bind-api
    version: 3.0.0
    obr: true
    mvp: true
    isolated: true
    
  - group: javax.validation
    artifact: validation-api
    version: 2.0.1.Final
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - group: org.apache.bcel
    artifact: bcel
    version: 6.3
    obr: true
    mvp: true
    isolated: true
    
  - group: org.apache.commons
    artifact: commons-collections4
    version: 4.4
    obr: true
    isolated: true
    
  - group: org.apache.commons 
    artifact: commons-compress 
    version: 1.19 
    obr: true 
    mvp: true
    isolated: true
    
  - group: org.apache.commons
    artifact: commons-lang3
    version: 3.8.1
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - group: org.apache.derby 
    artifact: derbyclient 
    version: 10.14.2.0 
    obr: true 
    
  - group: org.apache.felix
    artifact: org.apache.felix.configadmin
    version: 1.9.16
    obr: true
    mvp: true
    isolated: true
    
  - group: org.apache.felix
    artifact: org.apache.felix.gogo.command
    version: 1.1.0
    obr: true
    mvp: true
    isolated: true
    
  - group: org.apache.felix
    artifact: org.apache.felix.gogo.runtime
    version: 1.1.2
    obr: true
    mvp: true
    isolated: true
    
  - group: org.apache.felix
    artifact: org.apache.felix.gogo.shell
    version: 1.1.2
    obr: true
    mvp: true
    isolated: true
    
  - group: org.apache.felix
    artifact: org.apache.felix.http.servlet-api
    version: 1.1.2
    obr: true
    mvp: true
    isolated: true
    
  - group: org.apache.felix
    artifact: org.apache.felix.http.jetty
    version: 4.0.14
    obr: true
    isolated: true
    
  - group: org.apache.felix
    artifact: org.apache.felix.fileinstall
    version: 3.6.4
    obr: true
    isolated: true
    
  - group: org.apache.httpcomponents
    artifact: httpclient-osgi
    version: 4.5.13
    obr: true
    bom: true
    isolated: true
    mvp: true
    
  - group: org.apache.httpcomponents
    artifact: httpcore-osgi
    version: 4.4.14
    obr: true
    bom: true
    isolated: true
    mvp: true
    
  - group: org.apache.velocity 
    artifact: velocity
    version: 1.7 
    obr: true
    mvp: true
    isolated: true
    
  - group: org.assertj
    artifact: assertj-core
    version: 3.11.1
    obr: true
    bom: true
    mvp: true
    isolated: true
    
  - group: org.osgi 
    artifact: org.osgi.service.component.annotations 
    version: 1.3.0 
    bom: true 

  - group: org.yaml 
    artifact: snakeyaml 
    version: 1.29
    obr: true 
    isolated: true
