#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gradle-repo-build
  namespace: galasa-tekton
spec:
  workspaces:
  - name: git-workspace
    optional: false
  params:
  - name: distBranch
    type: string
  - name: refspec
    type: string
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "false"
  - name: isRelease
    type: string
    default: "false"
  tasks:
  - name: clone-gradle
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/gradle
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: gradle
    workspaces:
     - name: output
       workspace: git-workspace
  - name: gradle-compile
    taskRef:
      name: gradle-repo-build
    runAfter:
    - clone-gradle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: noPush
      value: $(params.noPush)
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-deployment
    taskRef:
      name: recycle-deployment
    runAfter:
    - gradle-compile
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-branch-$(params.distBranch)
    - name: deployment
      value: maven-$(params.distBranch)-gradle
