#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-maven-
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    value: main
  - name: version
    value: 0.15.0
  - name: gradleVersion
    value: 0.15.0
  pipelineRef:
    name: maven-repo-build
  serviceAccountName: build-bot
  resources:
  - name: git-maven
    resourceRef:
      name: git-maven-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
    volumes:
    - name: mavengpg
      secret:
        secretName: mavengpg
