apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: obr-repo-build
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    type: string
  - default: https://artifactory-cicsk8s.hursley.ibm.com/artifactory/maven-proxy/
    name: mavenCentralRepo
    type: string
  - default: https://repo.maven.apache.org/maven2/
    name: managersSourceRepo
    type: string
  - default: harbor-cicsk8s.hursley.ibm.com
    name: dockerRepo
    type: string
  - default: ""
    name: noPush
    type: string
  steps:
  - command:
    - mkdir
    - /workspace/gpg
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: gpgdirectory
    resources: {}
    workingDir: /workspace
  - command:
    - gpg
    - --homedir
    - /workspace/gpg
    - --pinentry-mode
    - loopback
    - --passphrase-file
    - /root/mavengpg/galasa.passphrase
    - --import
    - /root/mavengpg/galasa.gpg
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: import-gpg
    resources: {}
    volumeMounts:
    - mountPath: /root/mavengpg
      name: mavengpg
    workingDir: /workspace
  - command:
    - cp
    - /root/mavengpg/settings.xml
    - /workspace/gpg/settings.xml
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: copy-settings
    resources: {}
    volumeMounts:
    - mountPath: /root/mavengpg
      name: mavengpg
    workingDir: /workspace
  - image: $(params.dockerRepo)/galasadev/galasa-build
    name: get-commit
    resources: {}
    script: |
      #!/bin/sh
      set +e
      COMMIT="$(git log --format="%H" -n 1)"
      echo $COMMIT > /workspace/git/obr/docker/obr.githash
      echo commit is $COMMIT
    workingDir: /workspace/git/obr
  - command:
    - galasabld
    - template
    - --releaseMetadata
    - /workspace/git/framework/release.yaml
    - --releaseMetadata
    - /workspace/git/extensions/release.yaml
    - --releaseMetadata
    - /workspace/git/managers/release.yaml
    - --releaseMetadata
    - /workspace/git/obr/release.yaml
    - --template
    - pom.template
    - --output
    - pom.xml
    - --bom
    image: $(params.dockerRepo)/galasadev/galasa-build:latest
    name: generate-bom
    resources: {}
    workingDir: /workspace/git/obr/galasa-bom
  - command:
    - cat
    - pom.xml
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: list-bom
    resources: {}
    workingDir: /workspace/git/obr/galasa-bom
  - command:
    - mvn
    - -Dgalasa.release.repo=file:/workspace/git/obr/docker/repo/
    - -Dgalasa.source.repo=$(params.managersSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - --settings
    - /workspace/gpg/settings.xml
    - -B
    - -e
    - -fae
    - deploy
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: bom-build
    resources: {}
    workingDir: /workspace/git/obr/galasa-bom
  - command:
    - galasabld
    - template
    - --releaseMetadata
    - /workspace/git/framework/release.yaml
    - --releaseMetadata
    - /workspace/git/extensions/release.yaml
    - --releaseMetadata
    - /workspace/git/managers/release.yaml
    - --releaseMetadata
    - /workspace/git/obr/release.yaml
    - --template
    - pom.template
    - --output
    - pom.xml
    - --obr
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: generate-obr
    resources: {}
    workingDir: /workspace/git/obr/dev.galasa.uber.obr
  - command:
    - cat
    - pom.xml
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: list-obr
    resources: {}
    workingDir: /workspace/git/obr/dev.galasa.uber.obr
  - command:
    - mvn
    - -Dgalasa.release.repo=file:/workspace/git/obr/docker/repo/
    - -Dgalasa.source.repo=$(params.managersSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - --settings
    - /workspace/gpg/settings.xml
    - -B
    - -e
    - -fae
    - deploy
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: obr-build
    resources: {}
    workingDir: /workspace/git/obr/dev.galasa.uber.obr
  - command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git/obr/docker
    - --destination=$(params.dockerRepo)/galasadev/galasa-maven-obr:$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git/obr/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=branch=$(params.distBranch)
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    name: docker-build
    resources: {}
    workingDir: /workspace/git/obr/docker
  workspaces:
  - mountPath: /workspace/git
    name: git-workspace
