apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: javadoc-build
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    type: string
  - default: 0.16.0
    name: mavenBaseVersion
    type: string
  - default: https://artifactory-cicsk8s.hursley.ibm.com/artifactory/maven-proxy/
    name: mavenCentralRepo
    type: string
  - default: https://repo.maven.apache.org/maven2/
    name: managersSourceRepo
    type: string
  - default: harbor-cicsk8s.hursley.ibm.com
    name: dockerRepo
    type: string
  - default: ""
    name: noPush
    type: string
  steps:
  - command:
    - galasabld
    - template
    - --releaseMetadata
    - /workspace/git/framework/release.yaml
    - --releaseMetadata
    - /workspace/git/extensions/release.yaml
    - --releaseMetadata
    - /workspace/git/managers/release.yaml
    - --releaseMetadata
    - /workspace/git/obr/release.yaml
    - --template
    - pom.template
    - --output
    - pom.xml
    - --javadoc
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: generate-pom
    resources: {}
    workingDir: /workspace/git/obr/javadocs
  - command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.release.repo=file:/workspace/git/obr/javadocs/docker/repo/
    - -Dgalasa.source.repo=$(params.managersSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dmaven.javadoc.failOnError=false
    - --settings
    - /workspace/git/obr/settings.xml
    - -B
    - -e
    - -fae
    - deploy
    image: $(params.dockerRepo)/galasadev/galasa-build
    name: javadoc-build
    resources: {}
    workingDir: /workspace/git/obr/javadocs
  - command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git/obr/javadocs
    - --destination=$(params.dockerRepo)/galasadev/galasa-javadocs:$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git/obr/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)/dockerhub
    - --build-arg=branch=$(params.distBranch)
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    name: javadoc-image-build
    resources: {}
    workingDir: /workspace/git/obr/javadocs
  - command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git/obr/javadocs/docker
    - --destination=$(params.dockerRepo)/galasadev/galasa-maven-javadoc:$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git-gradle/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=baseVersion=$(params.mavenBaseVersion)
    - --build-arg=branch=$(params.distBranch)
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    name: javadoc-repo-build
    resources: {}
    workingDir: /workspace/git/obr/javadocs/docker
  workspaces:
  - mountPath: /workspace/git
    name: git-workspace
