FROM harbor.galasa.dev/docker_proxy_cache/library/httpd:alpine

RUN rm -v /usr/local/apache2/htdocs/*
COPY dockerfiles/httpdconf/httpd.conf /usr/local/apache2/conf/httpd.conf

COPY javadocs/target/site/apidocs/ /usr/local/apache2/htdocs/