ARG dockerRepository
ARG tag

FROM ${dockerRepository}/galasadev/managers-maven-artefacts:${tag}

COPY obr/repo/ /usr/local/apache2/htdocs/
COPY obr.githash /usr/local/apache2/htdocs/obr.githash